import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { Amplify } from 'aws-amplify';
import './index.css';
import App from './App';

// amplify_outputs.json is generated by `npx ampx sandbox` — do not commit to git
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import outputs from '../amplify_outputs.json';

try {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const o = outputs as any;
  if (!o._PLACEHOLDER_) Amplify.configure(o);
} catch {
  console.warn('Amplify not configured — run `npx ampx sandbox` to generate amplify_outputs.json');
}

const queryClient = new QueryClient({
  defaultOptions: {
    queries: { staleTime: 2 * 60 * 1000, retry: 1 },
  },
});

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <QueryClientProvider client={queryClient}>
      <BrowserRouter>
        <App />
      </BrowserRouter>
    </QueryClientProvider>
  </StrictMode>
);
